#!/usr/bin/env ruby

def fix!(s)
  s.gsub!(/^http:\/\/docs\.oracle\.com\/javase\/specs\/jls\/se7\/html\/jls-.*\.html\#jls-([0-9.]*)$/, '{{java-language-specification|\1}}')
  s.gsub!(/^http:\/\/(?:www\.)?ruby-doc.org\/core-[0-9.]+\/(.*?)\.html$/, '{{ruby-doc-core|\1}}')
  s.gsub!(/^http:\/\/(?:www\.)?ruby-doc.org\/core-[0-9.]+\/(.*?)\.html#(.*?)$/, '{{ruby-doc-core|\1|\2}}')
end

Dir.glob('**/*ref') { |fn|
  body = File.read(fn)
  body_old = body.dup

  fix!(body)

  print "#{fn}\t"

  if body != body_old
    File.open(fn, 'w') { |f|
      f.write(body)
    }
    puts 'FIXED'
  else
    puts 'ok'
  end
}
